on : push
jobs : 
      first-job:
          runs-on : ubuntu-latest
          steps : 
                - uses : actions/checkout@v3
                - run : npx eslint .
                - run : node index.js